-- Create Departments Table
CREATE TABLE Departments (
    DepartmentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DepartmentName NVARCHAR2(50) NOT NULL UNIQUE,
    ManagerID NUMBER
);

-- Create Employees Table
CREATE TABLE Employees (
    EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName NVARCHAR2(50) NOT NULL,
    LastName NVARCHAR2(50) NOT NULL,
    DepartmentID NUMBER NOT NULL,
    Salary NUMBER(10,2) CONSTRAINT chk_salary CHECK (Salary >= 0),
    CONSTRAINT fk_department FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID)
);

-- Create LeaveRequests Table
CREATE TABLE LeaveRequests (
    LeaveID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmployeeID NUMBER NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    Reason NVARCHAR2(100),
    Status NVARCHAR2(20) CONSTRAINT chk_status CHECK (Status IN ('Pending', 'Approved', 'Rejected')),
    CONSTRAINT fk_employee FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID)
);

-- Create Instructors Table
CREATE TABLE Instructors (
    InstructorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName NVARCHAR2(50) NOT NULL,
    LastName NVARCHAR2(50) NOT NULL
);

-- Create TrainingCourses Table
CREATE TABLE TrainingCourses (
    CourseID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CourseName NVARCHAR2(100) NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    InstructorID NUMBER NOT NULL,
    CONSTRAINT fk_instructor FOREIGN KEY (InstructorID) REFERENCES Instructors(InstructorID)
);

